"""add recruit channels to users

Revision ID: 4fbc3fb5cde0
Revises: 7d8191e70530
Create Date: 2025-11-22 17:48:29.647147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbc3fb5cde0'
down_revision: Union[str, Sequence[str], None] = '7d8191e70530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recruit_text_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('recruit_voice_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recruit_voice_channel_id')
    op.drop_column('users', 'recruit_text_channel_id')
    # ### end Alembic commands ###
