"""add is_admin and fix status default

Revision ID: 764b00f658fd
Revises: 403f8c5c75dd
Create Date: 2025-11-17 22:29:11.266414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764b00f658fd'
down_revision: Union[str, Sequence[str], None] = '403f8c5c75dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
